# Generated by Django 6.0.1 on 2026-01-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Short description for the card')),
                ('icon_image', models.ImageField(help_text='Upload the SVG or PNG icon', upload_to='services/icons/')),
                ('cover_image', models.ImageField(help_text='The background image for the card', upload_to='services/covers/')),
                ('order', models.IntegerField(default=0, help_text='Order to display on homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, help_text="e.g. 'Satisfied Patient' or 'Teacher'", max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='Star rating (1-5)')),
            ],
        ),
    ]
