# Generated by Django 6.0.1 on 2026-01-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_image',
            field=models.FileField(help_text='Upload SVG or PNG icon', upload_to='services/icons/'),
        ),
    ]
