# Generated by Django 6.0.1 on 2026-01-13 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text='Main reason for visit'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='examination_notes',
            field=models.TextField(blank=True, help_text='Physical examination findings'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='followup_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Private notes (only visible to doctor)'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='Recommended treatment'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='issued_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.CharField(blank=True, help_text='e.g., 30 tablets', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True, help_text="Doctor's diagnosis"),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Symptoms described by patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional instructions'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(help_text='e.g., 500mg, 10ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(choices=[('3_days', '3 Days'), ('5_days', '5 Days'), ('7_days', '7 Days'), ('10_days', '10 Days'), ('14_days', '14 Days'), ('21_days', '21 Days'), ('30_days', '30 Days'), ('60_days', '60 Days'), ('90_days', '90 Days'), ('ongoing', 'Ongoing'), ('other', 'Other (See Instructions)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_times_daily', 'Three Times Daily'), ('four_times_daily', 'Four Times Daily'), ('every_4_hours', 'Every 4 Hours'), ('every_6_hours', 'Every 6 Hours'), ('every_8_hours', 'Every 8 Hours'), ('every_12_hours', 'Every 12 Hours'), ('as_needed', 'As Needed'), ('before_meals', 'Before Meals'), ('after_meals', 'After Meals'), ('at_bedtime', 'At Bedtime'), ('other', 'Other (See Instructions)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions'),
        ),
    ]
