# Generated by Django 6.0.1 on 2026-01-23 21:08

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Uploaded PDF of the prescription', null=True, storage=records.models.PrivateMediaStorage(), upload_to='prescriptions/%Y/%m/'),
        ),
    ]
