# Generated by Django 6.0.1 on 2026-01-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_video_host_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='video_host_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='video_room_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
