# Generated by Django 6.0.1 on 2026-01-13 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options_and_more'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG/EKG'), ('blood_test', 'Blood Test'), ('vaccination', 'Vaccination Record'), ('insurance', 'Insurance Document'), ('referral', 'Referral Letter'), ('discharge', 'Discharge Summary'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(upload_to='medical_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(blank=True, help_text='List all known allergies')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Diabetes, hypertension, etc.')),
                ('current_medications', models.TextField(blank=True, help_text='Currently taking medications')),
                ('past_surgeries', models.TextField(blank=True, help_text='List of past surgeries')),
                ('family_history', models.TextField(blank=True, help_text='Family medical history')),
                ('smoking_status', models.CharField(choices=[('never', 'Never'), ('former', 'Former Smoker'), ('current', 'Current Smoker')], default='never', max_length=10)),
                ('alcohol_consumption', models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], default='none', max_length=10)),
                ('exercise_frequency', models.CharField(blank=True, help_text='How often do you exercise?', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('surgery', 'Surgery'), ('hospitalization', 'Hospitalization'), ('vaccination', 'Vaccination'), ('injury', 'Injury'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical histories',
                'ordering': ['-event_date'],
            },
        ),
    ]
