# Generated by Django 6.0.1 on 2026-01-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_medicaldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
    ]
