# Generated by Django 6.0.1 on 2026-01-23 09:24

import records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_medicaldocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(storage=records.models.PrivateMediaStorage(), upload_to='documents/%Y/%m/'),
        ),
    ]
